pipeline {
    agent any
    
    options {
        timestamps()
        disableConcurrentBuilds()
    }
    
    environment {
    TF_IN_AUTOMATION = "true"
        }
    
    stages {
        stage('Verify Workspace') {
            steps {
                sh '''
                    pwd
                    ls -la
                '''
            }
        }
        stage('Terraform Init') {
            steps {
                dir('Terraform') {
                    sh '''
                        terraform init \
                            -input=false \
                            -no-color
                    '''
                }
            }
        }
        stage('Terraform Validate') {
            steps {
                dir('Terraform') {
                    sh '''
                        terraform validate \
                        -no-color
                    '''
                }
            }
        }
        stage('Terraform Plan') {
            steps {
                dir('Terraform') {
                    script {
                        sh '''
                            set +e
                            terraform plan \
                            -detailed-exitcode \
                            -no-color \
                            > plan.log 2>&1
                            echo $? > tf_exit
                        '''
                env.PLAN_EXIT = readFile('tf_exit').trim()
                echo "Terraform Plan Exit Code: ${env.PLAN_EXIT}"
                    }
                }
            }
        }
    }
}
