pipeline {
    agent any

    options {
        timestamps()
        disableConcurrentBuilds()
    }

    environment {
        ENVIRONMENT = "dev"
        TF_IN_AUTOMATION = "true"
    }

    stages {

        stage('Verify Workspace') {
            steps {
                sh '''
                    pwd
                    ls -la
                '''
            }
        }

        stage('Terraform Init') {
            steps {
                dir('Terraform') {
                    sh '''
                        terraform init \
                            -input=false \
                            -no-color
                    '''
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir('Terraform') {
                    sh '''
                        terraform validate \
                            -no-color
                    '''
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('Terraform') {
                    script {

                        sh '''
                            set +e
                            terraform plan \
                            -detailed-exitcode \
                            -no-color \
                            -out=tfplan > plan.log 2>&1
                            echo $? > tf_exit
                            
                            #Optional features
                            terraform show -no-color tfplan > full-plan.log
                            echo "========== Terraform Drift Summary ==========" > summary.log
                            grep -A50 -E "^  #|^Plan:" full-plan.log >> summary.log
                            
                        '''
                        
                        env.PLAN_EXIT = readFile('tf_exit').trim()
                        currentBuild.description = "Terraform Plan Exit Code: ${env.PLAN_EXIT}"
                        echo "Terraform Plan Exit Code: ${env.PLAN_EXIT}"
                        //Optional features
                        echo "========== Terraform Plan Summary =========="
                            sh '''
                                if [ -s summary.log ]; then
                                    cat summary.log
                                else
                                    echo "No summary generated"
                                fi
                                '''
                        echo "============================================"
                        archiveArtifacts artifacts: 'plan.log,full-plan.log,summary.log,tfplan.log'

                        if (env.PLAN_EXIT == "0") {
                            echo "No Drift detected"
                        } 
                        else if (env.PLAN_EXIT == "2") {
                            unstable("Terraform Drift detected")
                        } 
                        else {
                            error("Terraform Plan failed")
                        }
                    }
                }
            }
        }
    }

    post {

        success {
            echo "No Drift"
        }
        unstable {
            echo "Terraform Drift detected"
        }
        failure {
            echo "Terraform Pipeline Failed"
        }
        always {
            cleanWs()
        }
    }
}
