pipeline {

    agent any

    stages {

        stage('Checkout Repository') {

            steps {

                git(
                    branch: 'main',
                    credentialsId: 'github-pat',
                    url: 'https://github.com/Srikara-lolla/Projects.git'
                )

            }

        }

        stage('Verify Workspace') {

            steps {

                sh '''
                    echo "Workspace:"
                    pwd

                    echo ""
                    echo "Repository Contents:"
                    ls -la
                '''

            }

        }

        stage('Verify Terraform Directory') {

            steps {

                dir('Terraform') {

                    sh '''
                        echo "Terraform Directory:"
                        pwd

                        echo ""
                        echo "Terraform Files:"
                        ls -la

                        terraform --version
                    '''

                }

            }

        }

    }

}
